apiVersion: apps/v1
kind: Deployment
metadata:
  name: andelachallenge-react
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      andela: react-app
  template:
    metadata:
      labels:
        andela: react-app
    spec:
      containers:
      - name: andela-react-app
        image: drinkingjava/andela-challenge:1.0
---
apiVersion: v1
kind: Service
metadata:
  name: andela-react-app-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    andela: react-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001

